version: '3'
services:
  ros2-container:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    tty : true
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/siddharth/ros_ws:/workspaces/ros_ws/  # Mount the local scripts directory into the container
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    command: >
      bash -c "
      cd workspaces/ros_ws &&
      ./run_demo.sh
      "